name: ctfd-app
region: nyc
services:
- name: ctfd
  github:
    repo: b45t3rr/CTFd # Asegúrate de reemplazar esto con tu repositorio real
    branch: main
    deploy_on_push: true
  environment_slug: dockerfile # Utiliza 'dockerfile' si tienes un Dockerfile personalizado
  http_port: 8000
  instance_size_slug: basic-xxs
  instance_count: 1
  envs:
    - key: UPLOAD_FOLDER
      value: /var/uploads
    - key: DATABASE_URL
      value: mysql+pymysql://ctfd:ctfd@db/ctfd
    - key: REDIS_URL
      value: redis://cache:6379
    - key: WORKERS
      value: "1"
    - key: LOG_FOLDER
      value: /var/log/CTFd
    - key: ACCESS_LOG
      value: "-"
    - key: ERROR_LOG
      value: "-"
    - key: REVERSE_PROXY
      value: "true"
  routes:
    - path: /

- name: nginx
  image:
    name: nginx:stable
  environment_slug: dockerfile
  http_port: 80
  routes:
    - path: /
  envs:
    - key: NGINX_HOST
      value: nginx

databases:
- name: db
  engine: MYSQL
  version: "10.4"
  production: true
  envs:
    - key: MYSQL_ROOT_PASSWORD
      value: ctfd
    - key: MYSQL_USER
      value: ctfd
    - key: MYSQL_PASSWORD
      value: ctfd
    - key: MYSQL_DATABASE
      value: ctfd

- name: cache
  engine: REDIS
  version: "6"
  production: true

alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED

features:
- buildpack-stack=ubuntu-22
